version: '3'

networks:
  spark-network:
    driver: bridge

services:
  thrift-server:
    image: snowplow/spark-s3-iceberg:latest
    ports:
      - '10000:10000'
      - '4040:4040'
    environment:
      - SPARK_LOCAL_IP=thrift-server
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - ./spark-defaults.conf:/spark/conf/spark-defaults.conf.template
      - ./setup.sh:/setup.sh
    entrypoint: ["/bin/bash", "/setup.sh"]
    command: ["/bin/bash", "-c", "/spark/sbin/start-thriftserver.sh --master local[4] --driver-memory 8g --hiveconf hive.server2.thrift.port=10000 --hiveconf hive.server2.thrift.bind.host=0.0.0.0"]
    networks:
      - spark-network